### ISSUE TITLE
Application rootElement?

### ISSUE THREAD

**Issue by tonycoco** [stonecircle/ember-body-class#1]
Instead of slapping the classes on `<body>` shouldn't it be put onto `rootElement`?

**Comment by tonycoco** [comment]
Either way, it might be a nice option to do that :)

**Comment by jalcine** [comment]
[**@tonycoco**](https://github.com/tonycoco) commented on [Sep 18, 2015, 12:57 AM EDT](https://github.com/AddJam/ember-body-class/issues/1#issue-107133758 "2015-09-18T04:57:48Z - Replied by Github Comment Enhancer"):
> Instead of slapping the classes on `&lt;body&gt;` shouldn't it be put onto `rootElement`?

If that happens, this package might have to be renamed to be more accurate! :stuck_out_tongue:

**Comment by tonycoco** [comment]
True! :)

**Comment by mansona** [comment]
I would agree with @jalcine and say that it would probably need to be a new package 😂 also I'm not sure what extra functionality you might be able to achieve putting the class on the application instead of the body 🤔 

I'm closing this for now. Let me know if people think it needs to be re-opened
