### ISSUE TITLE
Object.freeze issue on IE11

### ISSUE THREAD

**Issue by ctjhoa** [stonecircle/ember-body-class#30]
Hi,

In this commit https://github.com/stonecircle/ember-body-class/commit/1df34bb5d6aaa7df7fc34ddfe12c5bfceea00254 you defined `bodyClasses` with `Object.freeze`.

This cause issue in our app for IE11 like so:
![2019-05-20-142534_1603x964_scrot](https://user-images.githubusercontent.com/1716173/58028945-28bf6780-7b0b-11e9-93ca-fe4bb41145e5.png)

And IE11 refuse to boot the app.

If I remove the `Object.freeze` constraint, the app boot normally.

Why this constraint has been introduced in the first place?
Will you accept a PR for removing it?

**Comment by mansona** [comment]
@ctjhoa thanks for the issue, yes that's a great catch and I would be very open to a PR fixing this 👍

**Comment by ctjhoa** [comment]
@mansona Any time to check my PR?
